version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard.yml

env:
  global:
    - COMPOSER_ROOT_VERSION="4.x-dev"
    - REQUIRE_RECIPE="4.x-dev"

# Using a manual matrix to exlude PHPUNIT_COVERAGE_TEST for now because it was causing some strange issues
# e.g. https://travis-ci.com/github/silverstripe/silverstripe-framework/jobs/457096837
jobs:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPCS_TEST=1
        - PHPSTAN_TEST=1
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="framework"
        - COMPOSER_INSTALL_ARG="--prefer-lowest"
    - php: 7.2
      env:
        - DB=PGSQL
        - PDO=1
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - PHPUNIT_TEST="framework"
    - php: 7.3
      env:
        - DB=MYSQL
        - PDO=1
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="framework"
    - php: 7.3
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="cms"
    - php: 7.4
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="framework"
    - php: nightly
      env:
        - DB=MYSQL
        - REQUIRE_INSTALLER="$REQUIRE_RECIPE"
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="framework"
        - COMPOSER_INSTALL_ARG="--ignore-platform-reqs"
